### ISSUE TITLE
Accessing addr 0x0000001e doesn't throw access fault exception

### ISSUE THREAD

**Issue by zhangkanqi** [SpinalHDL/NaxRiscv#108]
Hi,

I found that when accessing addr 0x0000001e, NaxRiscv doesn't throw access fault exception. This might be a pretty obvious bug.

By the way, could you offer the address map in NaxRiscv like the following format? I didn't find that either in docs and source codes. Thanks a lot.

<img src="https://github.com/SpinalHDL/NaxRiscv/assets/34207592/12cc300d-8d9a-4452-93f8-c7bd9eb2bbfd" width="70%">

**Comment by Dolu1990** [comment]
Hi,

The NaxRiscv default regions are : 
              ioRange    : UInt => Bool = _(31 downto 28) === 0x1,
              fetchRange : UInt => Bool = _(31 downto 28) =/= 0x1,
              
Meaning [0x1000_0000, 0x1FFF_FFFF] is io mapped, and also can't be used to execute instruction
There is a few peripherals emulated in that range.

 [0x000_0000, 0x0FFF_FFFF] is cached but will always return fault by the testbench
 [0x200_0000, 0xFFFF_FFFF] is cached and always ok

NaxRiscv will not give you a fault on cached memory store.
So the issue you have is expected by design. The reason is that memory store happen after commit for performance reason.
