### ISSUE TITLE
Issue with Make Compile in setup

### ISSUE THREAD

**Issue by Pavitra07** [SpinalHDL/NaxRiscv#34]
On running make compile, i get the following errors. Kindly help.
![Screenshot from 2023-06-22 12-06-28](https://github.com/SpinalHDL/NaxRiscv/assets/68284614/4ef82f60-3f6f-4083-a4f2-56af7c0d0179)

**Comment by Dolu1990** [comment]
Hi,

which version of GCC do you have ?

(me gcc 10.1.0)

**Comment by Pavitra07** [comment]
Hello,

I have the following version:

gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)

**Comment by Dolu1990** [comment]
Ahh it may bit it, string_view seems to be from C++17, gcc 9.4 may be too old ?

**Comment by Pavitra07** [comment]
I have upgraded it to the following:
gcc version 10.3.0 (Ubuntu 10.3.0-1ubuntu1~20.04) 
Still showing the same error for make compile.
Should I restart the process?

**Comment by Dolu1990** [comment]
hmm pretty sure it is related to  different version of GCC / C++ library.
Issue is that string_view seems c++ 17, but verilator is only c++ 14, so kind of a missmatch XD

Looking at https://github.com/verilator/verilator/issues/3081, seems like it may not be compatible with C++20
May worth a try ?

Getting a Very recent verilator version, and updating https://github.com/SpinalHDL/NaxRiscv/blob/6d1d48379609c5a390f8f4f02527282b21b311b6/src/test/cpp/naxriscv/makefile#L81   with -std=c++20 instead of -std=c++14 ?

**Comment by Pavitra07** [comment]
I did the update in the make file regarding c++20, but still facing the same errors. Is there any way I could get through this?

**Comment by Dolu1990** [comment]
Found it :)

So, there was a elfio update which broke things.

You just need to reinstall elfio by : 

```
sudo rm -rf /usr/include/elfio
git clone https://github.com/serge1/ELFIO.git
cd ELFIO
git checkout d251da09a07dff40af0b63b8f6c8ae71d2d1938d # Avoid C++17
sudo cp -R elfio /usr/include
```

**Comment by Pavitra07** [comment]
Thanks a lot for the help! This absolutely worked :)
